import type { ChoreRule, DashboardSections, DayKey, MemberId, RotationConfig, RotationWeekKey, TaskInstance } from "./types";
export const dayNames=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
export const dayShort=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export const dayKeys:DayKey[]=["mon","tue","wed","thu","fri","sat","sun"];
const rotationKeys:RotationWeekKey[]=["A","B","C"];
export function addDays(date:Date,days:number):Date{const d=new Date(date);d.setDate(d.getDate()+days);return d;}
export function toISODate(date:Date):string{const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,"0");const d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`;}
export function parseLocalDate(iso:string):Date{const [y,m,d]=iso.split("-").map(Number);return new Date(y,m-1,d);}
export function dayIndexFromDate(date:Date):number{return (date.getDay()+6)%7;}
export function getMonday(date:Date):Date{return addDays(date,-dayIndexFromDate(date));}
export function daysBetween(start:Date,end:Date):number{const a=new Date(start.getFullYear(),start.getMonth(),start.getDate());const b=new Date(end.getFullYear(),end.getMonth(),end.getDate());return Math.round((b.getTime()-a.getTime())/86400000);}
export function cycleKeys(config:RotationConfig):RotationWeekKey[]{return rotationKeys.slice(0,config.cycleLength);}
export function cycleWeekForOffset(config:RotationConfig,weekOffset:number):RotationWeekKey{const keys=cycleKeys(config);return keys[weekOffset%keys.length];}
export function rotationDescription(config:RotationConfig):string{return config.cycleLength===1?"1-week cycle":config.cycleLength===2?"2-week cycle":"3-week cycle";}
export function assignedMemberForDaily(config:RotationConfig,weekOffset:number,day:number):string{const weekKey=cycleWeekForOffset(config,weekOffset);return config.weeks[weekKey][dayKeys[day]];}
export function isOpenIssue(task:TaskInstance):boolean{return ["swap_requested","unable","overdue"].includes(task.status);}
export function isDone(task:TaskInstance):boolean{return ["done","reassigned","cancelled"].includes(task.status);}
export function isAvailable(task:TaskInstance):boolean{return task.type==="one_off"&&task.status==="available";}
export function taskDueDate(task:TaskInstance):Date{return parseLocalDate(task.dueDate);}
export function taskIsDueOn(task:TaskInstance,date:Date):boolean{return task.dueDate===toISODate(date);}
export function taskMatchesWeekDay(task:TaskInstance,weekStart:Date,dayIndex:number):boolean{return daysBetween(weekStart,taskDueDate(task))===dayIndex;}
export function taskFallsInWeek(task:TaskInstance,weekStart:Date):boolean{const diff=daysBetween(weekStart,taskDueDate(task));return diff>=0&&diff<7;}
export function taskDateLabel(task:TaskInstance):string{const due=taskDueDate(task);const date=`${dayNames[dayIndexFromDate(due)]} ${due.getDate()} ${due.toLocaleString("en-AU",{month:"short"})}`;const time=task.dueTime?` · due ${task.dueTime}`:"";const cycle=task.rotationWeek?` · Week ${task.rotationWeek}`:"";return `${date}${time}${cycle}`;}
export function descriptionLines(text:string):string[]{return text.split("\n").map(s=>s.trim()).filter(Boolean);}
export function dashboardSections(tasks:TaskInstance[],currentMember:MemberId,weekStart:Date,today:Date=new Date()):DashboardSections{const relevant=tasks.filter(t=>isAvailable(t)||t.assignedTo===currentMember||isOpenIssue(t));const todayISO=toISODate(today);return{today:relevant.filter(t=>t.dueDate===todayISO&&!isOpenIssue(t)&&!isDone(t)&&!isAvailable(t)),thisWeek:relevant.filter(t=>{if(!taskFallsInWeek(t,weekStart))return false;if(t.dueDate===todayISO)return false;return!isOpenIssue(t)&&!isDone(t)&&!isAvailable(t)}),available:tasks.filter(t=>isAvailable(t)&&taskFallsInWeek(t,weekStart)),requests:relevant.filter(isOpenIssue),done:relevant.filter(isDone)}}
export function generateRecurringTaskInstances(choreRules:ChoreRule[],rotation:RotationConfig,startMonday:Date,weeksToGenerate=6):TaskInstance[]{const now=new Date().toISOString();const tasks:TaskInstance[]=[];for(let weekOffset=0;weekOffset<weeksToGenerate;weekOffset++){const weekStart=addDays(startMonday,weekOffset*7);const weekStartISO=toISODate(weekStart);const rotationWeek=cycleWeekForOffset(rotation,weekOffset);for(const rule of choreRules.filter(r=>r.active)){if(rule.frequency==="Daily"){for(let day=0;day<7;day++){const dueDate=toISODate(addDays(weekStart,day));tasks.push({id:`gen_${rule.id}_${dueDate}`,type:"recurring",choreRuleId:rule.id,name:rule.name,icon:rule.icon,frequency:rule.frequency,assignedTo:assignedMemberForDaily(rotation,weekOffset,day),dueDate,status:day===0&&weekOffset===0?"pending":"upcoming",description:rule.description,rotationWeek,weekStart:weekStartISO,generated:true,createdAt:now,updatedAt:now})}}else if(rule.frequency==="Weekly"||(rule.frequency==="Fortnightly"&&weekOffset%2===0)||(rule.frequency==="Monthly"&&weekOffset===0)){const dueDate=toISODate(addDays(weekStart,rule.day));tasks.push({id:`gen_${rule.id}_${dueDate}`,type:"recurring",choreRuleId:rule.id,name:rule.name,icon:rule.icon,frequency:rule.frequency,assignedTo:rule.assignedTo,dueDate,status:weekOffset===0?"pending":"upcoming",description:rule.description,weekStart:weekStartISO,generated:true,createdAt:now,updatedAt:now})}}}return tasks;}
