import { collection, deleteDoc, doc, getDocs, onSnapshot, orderBy, query, setDoc, updateDoc, writeBatch } from "firebase/firestore";
import { signInAnonymously } from "firebase/auth";
import { auth, db } from "../lib/firebase";
import type { ActivityEntry, ChoreRule, Member, MemberId, RotationConfig, TaskInstance, TaskStatus } from "../domain/types";
import { generateRecurringTaskInstances, getMonday, parseLocalDate, toISODate } from "../domain/rules";
import { HOUSEHOLD_ID, seedActivities, seedChoreRules, seedMembers, seedRotation, seedTasks } from "../data/seed";
const householdDoc=doc(db,"households",HOUSEHOLD_ID);const rotationDoc=doc(db,"households",HOUSEHOLD_ID,"config","rotation");function col(name:string){return collection(db,"households",HOUSEHOLD_ID,name)}
export async function ensureAnonymousAuth(){if(!auth.currentUser)await signInAnonymously(auth)}
export async function ensureSeedData(){await ensureAnonymousAuth();const memberDocs=await getDocs(col("members"));if(!memberDocs.empty)return;const batch=writeBatch(db);batch.set(householdDoc,{name:"Klein household",createdAt:new Date().toISOString()});seedMembers.forEach(m=>batch.set(doc(col("members"),m.id),m));seedChoreRules.forEach(c=>batch.set(doc(col("choreRules"),c.id),c));batch.set(rotationDoc,seedRotation);seedTasks().forEach(t=>batch.set(doc(col("tasks"),t.id),t));seedActivities().forEach(a=>batch.set(doc(col("activities"),a.id),a));await batch.commit()}
export function subscribeMembers(cb:(m:Member[])=>void){return onSnapshot(col("members"),snap=>cb(snap.docs.map(d=>d.data() as Member)))}
export function subscribeChoreRules(cb:(r:ChoreRule[])=>void){return onSnapshot(col("choreRules"),snap=>cb(snap.docs.map(d=>d.data() as ChoreRule)))}
export function subscribeTasks(cb:(t:TaskInstance[])=>void){return onSnapshot(query(col("tasks"),orderBy("dueDate","asc")),snap=>cb(snap.docs.map(d=>d.data() as TaskInstance)))}
export function subscribeActivities(cb:(a:ActivityEntry[])=>void){return onSnapshot(query(col("activities"),orderBy("createdAt","desc")),snap=>cb(snap.docs.map(d=>d.data() as ActivityEntry)))}
export function subscribeRotation(cb:(r:RotationConfig)=>void){return onSnapshot(rotationDoc,snap=>{if(snap.exists())cb(snap.data() as RotationConfig)})}
export async function addActivity(actorId:MemberId,text:string,type:ActivityEntry["type"],taskId?:string){const now=new Date().toISOString();const id=`activity_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;await setDoc(doc(col("activities"),id),{id,type,actorId,text,taskId,createdAt:now,weekStart:toISODate(getMonday(new Date()))})}
export async function updateTaskStatus(task:TaskInstance,status:TaskStatus,actorId:MemberId,reason?:string,swapTarget?:MemberId){await updateDoc(doc(col("tasks"),task.id),{status,reason:reason||"",swapTarget:swapTarget||"",updatedAt:new Date().toISOString()});await addActivity(actorId,`${actorName(actorId)} updated ${task.name} to ${status}${reason?`: ${reason}`:""}.`,status==="done"?"done":"updated",task.id)}
export async function claimTask(task:TaskInstance,actorId:MemberId){await updateDoc(doc(col("tasks"),task.id),{assignedTo:actorId,status:"pending",updatedAt:new Date().toISOString()});await addActivity(actorId,`${actorName(actorId)} took one-off task: ${task.name}.`,"claimed",task.id)}
export async function createOneOffTask(input:{name:string;assignedTo:MemberId;dueDate:string;dueTime?:string;description:string;createdBy:MemberId}){const now=new Date().toISOString();const id=`oneoff_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;const due=parseLocalDate(input.dueDate);const task:TaskInstance={id,type:"one_off",name:input.name,icon:"📌",frequency:"One-off",assignedTo:input.assignedTo,dueDate:input.dueDate,dueTime:input.dueTime||"",status:input.assignedTo==="anyone"?"available":"pending",description:input.description,createdBy:input.createdBy,weekStart:toISODate(getMonday(due)),createdAt:now,updatedAt:now};await setDoc(doc(col("tasks"),id),task);await addActivity(input.createdBy,`${actorName(input.createdBy)} created one-off task: ${input.name}. ${input.assignedTo==="anyone"?"Available for anyone.":"Assigned to "+actorName(input.assignedTo)+"."}`,"created",id)}
export async function saveRotation(rotation:RotationConfig,actorId:MemberId){await setDoc(rotationDoc,rotation);await addActivity(actorId,`${actorName(actorId)} saved the ${rotation.cycleLength}-week daily roster template assignments.`,"system")}
export async function addChoreRule(rule:ChoreRule,actorId:MemberId){await setDoc(doc(col("choreRules"),rule.id),rule);await addActivity(actorId,`${actorName(actorId)} added recurring chore: ${rule.name}.`,"created")}
export async function generateSixWeeks(choreRules:ChoreRule[],rotation:RotationConfig,actorId:MemberId){const existing=await getDocs(col("tasks"));const batch=writeBatch(db);existing.docs.map(d=>d.data() as TaskInstance).filter(t=>t.type==="recurring"&&t.generated).forEach(t=>batch.delete(doc(col("tasks"),t.id)));generateRecurringTaskInstances(choreRules,rotation,getMonday(new Date()),6).forEach(t=>batch.set(doc(col("tasks"),t.id),t));await batch.commit();await addActivity(actorId,`${actorName(actorId)} generated the next 6 weeks from recurring rules and rotation template.`,"system")}
export async function resetDemoData(){for(const name of ["members","choreRules","tasks","activities"]){const docs=await getDocs(col(name));await Promise.all(docs.docs.map(d=>deleteDoc(d.ref)))}await ensureSeedData()}
function actorName(id:MemberId):string{return id==="laurence"?"Laurence":id==="tom"?"Tom":id==="loretta"?"Loretta":"Anyone"}
